name: lint
on:
  push:
    branches:
      - main
  pull_request: ~
jobs:
  style:
    name: style
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check --config-path=.stylua.toml lua/
